name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # sizning asosiy branch nomi
  workflow_dispatch:

permissions:
  contents: write  # bu kerak bo‘lmasa push qilolmaydi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # agar React bo‘lsa: npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output   # yoki gh-pages
          build_dir: dist         # build chiqadigan papka nomi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
